base/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from base import views

urlpatterns = [
    url(r'^registrar/$', views.UserCreateView.as_view(), name='registrar'),
    url(r'^entrar/$', login, name='entrar'),    
    url(r'^sair/$', logout, {'next_page': 'index'}, name='sair'),
    url(r'^atualizar_usuario/$', 'base.views.atualizar_usuario', name='atualizar_usuario'),
    url(r'^usuarios/$', 'base.views.usuarios_to_csv', name='usuarios'),
]

eventos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from eventos.views import MaratonaProgramacaoCreate

urlpatterns = patterns(
    '',
    url(r'^$', 'eventos.views.index', name='index'),
    #url(r'^inscricao_desafio/$', login_required(MaratonaProgramacaoCreate.as_view(template_name="form.html")), name='inscricao_desafio'),
    #url(r'^atualizar_inscricao$', 'eventos.views.atualizar_maratona_programacao', name='atualizar_inscricao'),
    # url(r'^incricao_evento/(?P<pk>\d+)/$', 'eventos.views.inscrever_evento', name="inscricao_evento"),
    # url(r'^minha_area/$', 'eventos.views.area_usuario', name="minha_area"),
    # url(r'^submeter_trabalho/$', 'eventos.views.submeter_trabalho', name='submeter_trabalho'),
)

eventos/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.db import models
from djchoices.choices import DjangoChoices, ChoiceItem

from base.models import CustomUser


class Evento(models.Model):
    descricao = models.CharField(u"descrição", max_length=55)
    data_inicial = models.DateField(u"data inicial")
    data_final = models.DateField(u"data final")

    def __unicode__(self):
        return self.descricao


class Inscricao(models.Model):
    evento = models.ForeignKey(Evento, related_name="inscricoes")
    usuario = models.ForeignKey(CustomUser, related_name="inscricoes")

    def __unicode__(self):
        return self.evento.descricao

    class Meta:
        verbose_name = u"inscrição"
        verbose_name_plural = u"inscrições"
        unique_together = ('evento', 'usuario',)


class TipoTrabalho(models.Model):
    tipo = models.CharField("área", max_length=55)

    def __unicode__(self):
        return self.tipo

    class Meta:
        verbose_name = u"área"
        verbose_name_plural = u"áreas"


class Trabalho(models.Model):
    class Status(DjangoChoices):
        EmAvaliando = ChoiceItem(1, label=u"em avaliação")
        Reprovado = ChoiceItem(2, label=u"reprovado")
        Aprovado = ChoiceItem(3, label=u"aprovado")
        AprovadoComCorrecoes = ChoiceItem(4, label=u"aprovado com correções")

    inscricao = models.ForeignKey(Inscricao)
    tipo = models.ForeignKey(TipoTrabalho)
    titulo = models.CharField(verbose_name=u"título", max_length=100)
    autores = models.CharField(max_length=1000, help_text="Formato: nome1, CPF1; nome2, CPF2")
    orientadores = models.CharField(max_length=255)
    artigo = models.FileField(upload_to="articles/%Y-%m-%d")
    status = models.PositiveIntegerField(choices=Status.choices, default=Status.EmAvaliando)

    @property
    def str_status(self):
        return self.get_status_display()

    @property
    def email_do_autor(self):
        return self.inscricao.usuario.email

    @property
    def nome_do_autor(self):
        return self.inscricao.usuario.get_full_name()

    def __unicode__(self):
        return u'Título: %s - Status: %s' % (self.titulo, self.str_status)

    class Meta:
        ordering = ['status', 'titulo']


class MaratonaProgramacao(models.Model):

    class Turno(DjangoChoices):
        manha = ChoiceItem(1, "manhã")
        tarde = ChoiceItem(2, "tarde")
        noite = ChoiceItem(3, "noite")

    email = models.EmailField('e-mail de contato', unique=True, default="")
    nome_equipe = models.CharField(u"nome da equipe", max_length=50, unique=True)
    integrante1 = models.CharField(u"lider", max_length=255)
    integrante2 = models.CharField(u"nome do componente 1", max_length=255)
    integrante3 = models.CharField(u"nome do componente 2", max_length=255, blank=True, null=True)
    horario_treinamento = models.PositiveIntegerField(
        u"horário do treinamento", choices=Turno.choices, default=Turno.manha)

    def __unicode__(self):
        return self.nome_equipe

    class Meta:
        verbose_name = u"Maratona de Programação"
        verbose_name_plural = u"Maratona de Programação"

eventos/views.py
# -*- coding: utf-8 -*-
from datetime import date

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic.edit import CreateView

from eventos.form import TrabalhoForm, MaratonaProgramacaoForm
from eventos.models import Inscricao, Evento, Trabalho, MaratonaProgramacao


def index(request):
    return render(request, 'home.html')


@login_required
def inscrever_evento(request, pk):
    evento = Evento.objects.get(pk=pk)
    Inscricao(evento=evento, usuario=request.user).save()
    messages.add_message(request, messages.SUCCESS, "Inscrição realizada com sucesso.")
    return redirect(reverse_lazy('minha_area'))


@login_required
def area_usuario(request):
    novos_eventos = Evento.objects.exclude(inscricoes__usuario=request.user).filter(data_final__gte=date.today())
    eventos_inscritos = Evento.objects.filter(inscricoes__usuario=request.user, data_final__gte=date.today())
    trabalhos = Trabalho.objects.all().filter(inscricao__usuario=request.user)
    return render(request, 'area_usuario.html', {
        'novos_eventos': novos_eventos,
        'eventos_inscritos': eventos_inscritos,
        'trabalhos': trabalhos})


@login_required
def submeter_trabalho(request):
    if request.method == 'POST':
        form = TrabalhoForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Trabalho enviado com sucesso.")
            return redirect(reverse_lazy('minha_area'))
    else:
        form = TrabalhoForm(request.user)
    return render(request, 'submissao_artigo.html', {'form': form})


@login_required
def atualizar_maratona_programacao(request):
    inscricao = MaratonaProgramacao.objects.filter(email=request.user.email).first()

    if inscricao is None:
        return redirect(reverse_lazy('minicursos'))

    if request.method == 'POST':
        form = MaratonaProgramacaoForm(request.POST, instance=inscricao)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, u"Inscrição atualizada.")
            return redirect(reverse_lazy('minicursos'))
    else:
        form = MaratonaProgramacaoForm(instance=inscricao)
    return render(request, 'form.html', {'form': form})


class MaratonaProgramacaoCreate(CreateView):
    model = MaratonaProgramacao
    success_url = reverse_lazy('minicursos')
    fields = ('nome_equipe', 'integrante1', 'integrante2', 'integrante3', 'horario_treinamento',)

    def form_valid(self, form):
        form.instance.email = self.request.user.email
        return super(MaratonaProgramacaoCreate, self).form_valid(form)

eventos/templates/area_usuario.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extraheader %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block menu %}
    {% include 'menus/menu_area_usuario.html' %}
{% endblock %}


{% block content %}

    <section class="team-parlex" style="margin-top: 50px">
        <section class="parlex5-back">
            <div class="w-container">
                <div class="wrap">

                    {% include 'alert.html' %}

                    {% if novos_eventos %}
                        <div class="col-lg-12">
                            <ul class="list-group">
                                {% for evento in novos_eventos %}
                                    <li>
                                        <a class="btn btn-success"
                                           href="{% url 'eventos.views.inscrever_evento' evento.id %}">Inscreva-se: {{ evento.descricao }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                    {% if eventos_inscritos %}
                        <div class="col-lg-12">
                            <ul class="list-group">
                                {% for evento in eventos_inscritos %}
                                    <li><a class="btn btn-success"
                                           href="{% url 'eventos.views.submeter_trabalho' %}">Submeter
                                        artigo: {{ evento.descricao }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Documentos importantes
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <a class="btn btn-primary" href="{% static 'modelo_artigo.docx' %}">Modelo Artigo</a>
                                <a class="btn btn-primary" href="{% static 'modelo_banner.doc' %}">Modelo Banner</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Artigos submetidos
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th>Título</th>
                                            <th>Tipo</th>
                                            <th>Evento</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% if trabalhos %}
                                            {% for trabalho in trabalhos %}
                                                <tr>
                                                    <td>{{ trabalho.titulo }}</td>
                                                    <td>{{ trabalho.tipo }}</td>
                                                    <td>{{ trabalho.inscricao.evento }}</td>
                                                    <td>{{ trabalho.str_status }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        {% endif %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-2.js' %}"></script>

{% endblock %}

eventos/templates/form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block extraheader %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block menu %}
    {% if user.is_anonymous %}
        {% include 'menus/menu_nao_autenticado.html' %}
    {% else %}
        {% include 'menus/menu_autenticado.html' %}
    {% endif %}
{% endblock %}

{% block content %}
    <section class="team-parlex" id="hospitalidade">
        <section class="parlex5-back">
            <div class="w-container">
                <div class="wrap">

                    <h1 class="service-heading">Desafio de Programação</h1>

                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form_errors form %}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        {% endbuttons %}
                    </form>

                </div>
            </div>
            </div>
        </section>
    </section>
{% endblock %}

eventos/templates/home.html
{% extends "base.html" %}

{% block menu %}
    {% if user.is_anonymous %}
        {% include 'menus/menu_nao_autenticado.html' %}
    {% else %}
        {% include 'menus/menu_autenticado.html' %}
    {% endif %}
{% endblock %}

{% block content %}

    {% include 'includes/banner.html' %}
    {% include 'includes/sobre.html' %}    
    {% include 'includes/programacao.html' %}
    {% include 'includes/palestrantes.html' %}
    {% include 'includes/competicao.html' %}
    {% include 'includes/hospitalidade.html' %}
    {% include 'includes/organizadores.html' %}

{% endblock %}

eventos/templates/submissao_artigo.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block extraheader %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
{% endblock %}

{% block menu %}
    {% include 'menus/menu_area_usuario.html' %}
{% endblock %}

{% block content %}
    <section class="team-parlex" style="margin-top: 50px">
        <section class="parlex5-back">
            <div class="w-container">
                <div class="wrap">

                <div style="padding-bottom: 30px">
                    <a class="btn btn-default" href="{% url 'minha_area' %}">voltar</a>
                </div>

                    <div class="login-panel panel panel-default">
                        <div class="panel-heading">
                            <h2 class="panel-title">Cadastrar Trabalho</h2>
                        </div>
                        <div class="panel-body">
                            {% if form.errors %}
                                <div class="alert alert-danger">Email ou senha incorretos. Tente novamente.</div>
                            {% endif %}
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form_errors form %}
                                {% bootstrap_field form.inscricao %}
                                {% bootstrap_field form.tipo %}
                                {% bootstrap_field form.titulo %}

                                <input class="form-control" maxlength="1000" name="autores" type="hidden"/>
                                <input class="form-control" maxlength="255" name="orientadores" type="hidden"/>

                                <div class="container form-group">
                                    <label class="control-label">Autores</label>

                                    <div id="autor_fields">
                                        <div class="form-group" id="autor">
                                            <div class="form-group col-md-6">
                                                <input class="form-control" id="nome_autor_0" maxlength="100"
                                                       placeholder="Nome completo" required="required"/>
                                            </div>
                                            <div class="form-group col-md-4">
                                                <input class="form-control" id="cpf_autor_0" maxlength="11"
                                                       placeholder="CPF" required="required" pattern="\d{11}"/>
                                            </div>
                                            <div class="form-group col-md-1 btn btn-success add_autor">+Autor</div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label">Orientador</label>
                                    <input class="form-group form-control" id="nome_orientador_0" maxlength="100"
                                           placeholder="Nome completo" required="required"/>
                                    <input class="form-group form-control" id="cpf_orientador_0" maxlength="11"
                                           placeholder="CPF"
                                           required="required" pattern="\d{11}"/>
                                </div>


                                <label class="control-label" for="id_artigo">Artigo</label>

                                <div class="row bootstrap3-multi-input">
                                    <div class="col-xs-12">
                                        <input class="" id="id_artigo" name="artigo" title="" required="required"
                                               type="file" pattern="([^\s]+(\.(?i)(doc|docx))$)"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">
                                        Enviar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>

    <script>

        var num_autores = 1;

        function get_nome_cpf(nome, cpf, size) {
            var nome_cpf = ''
            for (i = 0; i < size; i++) {
                nome_cpf += "Nome: " + document.getElementById(nome + i).value + ", "
                nome_cpf += "CPF: " + document.getElementById(cpf + i).value + "; "
            }
            return nome_cpf
        }

        $("form").submit(function () {
            console.log("num" + num_autores)
            var autores = get_nome_cpf("nome_autor_", "cpf_autor_", num_autores)
            var orientadores = get_nome_cpf("nome_orientador_", "cpf_orientador_", 1)
            $('input[name="autores"]').attr('value', autores);
            $('input[name="orientadores"]').attr('value', orientadores);
            console.log(autores)
        });

        $(document).on('click', '#remover_autor', function () {
            $(this).parents("#autor").remove()
            num_autores -= 1;
            console.log(num_autores)
        });

        $('.add_autor').click(function () {
            var id_autor = num_autores
            var nome_cpf = '<div class="form-group" id="autor"><div class="form-group col-md-6">' +
                    '<input class="form-control" id="nome_autor_' + id_autor + '" maxlength="100" placeholder="Nome" required="required"/>' +
                    '</div><div class="form-group col-md-4">' +
                    '<input class="form-control" id="cpf_autor_' + id_autor + '" maxlength="11" placeholder="CPF" required="required" pattern="\\d{11}"/></div>' +
                    '<div class="form-group col-md-1 btn btn-warning add_autor" id="remover_autor">Remover</div></div>'
            $('#autor_fields').append(nome_cpf)
            num_autores += 1;
            console.log(num_autores)
        });
    </script>
{% endblock %}